Task: Home Form
alkemyTech/OT144-CLIENT pull request #1
Opened 2022-02-17 02:09 UTC by juliandebra

Home editor created: 

- Welcome message editor form.
- Slides editor form with text and image submit.

2022-02-17 12:45 UTC, federicomiranda requested changes
El import y la ruta están perfectamente agregados. Pero estás importando un componente que no existe. No se si te olvidaste de agregarlo al commit y no entró en el push, o si todavía es una tarea en progreso, pero si tiramos esto así a producción se rompe por importar un componente que no encuentra.

Y en otros aspectos más generales, siempre está bueno que en la descripción que dejas al crear el PR expliques en detalle lo que hiciste. Muchas veces la persona que te va a hacer code review no va a tener el mismo contexto que tenes vos de la tarea, entonces está bueno que se lo des antes de que empiece a revisar tu código.

2022-02-17 12:53 UTC, juliandebra commented
Mil disculpas, pensé que había agregado el archivo, pero se ve que solo hice "git add -p" y no "git add ."
Ahora sí hice un push con el archivo correspondiente. Debería cerrar este PR y abrir otro?

2022-02-17 23:17 UTC, federicomiranda commented on src/Components/Home/HomeForm.css
> +}
Si tenes tanto uso de flex, quizás te conviene hacer una clase que use las propiedades que usas siempre con los valores más comunes y aplicarle esa clase a los elementos para no estar escribiendo tantas veces lo mismo.

Igualmente es algo que se puede charlar con el equipo, por también va a pasar con otras cosas.

2022-02-17 23:23 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +  }
Estas 4 funciones se podrían resumir en una sola que por parámetros recib la validación, a que slide vamos a validar, y el error que queremos mostrar, y hagamos las cosas una única vez.

2022-02-17 23:24 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +      console.log(errorMessage);
No deberían llegar console logs a un pull request porque no queremos que después estén en producción cuando deployemos!

2022-02-17 23:28 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +            <input className='text-input' type='text' onChange={(e) =>  setWelcome(e.target.value)} /><br/>
No es una buena práctica el uso de la etiqueta br para generar saltos de línea. De toda la parte visual debería encargarse CSS.

2022-02-17 23:29 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +          <label>
Ojo con este label, está funcionando como contenedor y adentro tiene hasta un botón. El rol del label es simplemente tener un texto que acompañe al input. Si querés un contenedor podes usar un fieldset yo un div.

Los párrafos que están adentro del label, serían los verdaderos labels.

2022-02-17 23:30 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +          <label>
Idem el tema del label que comenté antes.

2022-02-17 23:31 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +          <label>
Idem el tema del label que comenté antes.

2022-02-17 23:32 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +            {thirdSlideError ? <p>{errorMessage}</p> : null}
Acá en vez de esto podes usar otra técnica de renderizado que no tiene un default como el ternario, podrías escribirlo como:

`{thirdSlideError && <p>{errorMessage}</p>}`

Obviamente lo mismo aplica para los de arriba, pero lo acabo de notar acá.

2022-02-17 23:34 UTC, federicomiranda requested changes
Hay varias cosas que se podrían mejorar, pero la resolución en general está bien y es válida. No hay nada demasiado polémico, salvo el tema de los labels de html que traería problemas a nivel semántico y accesibilidad. El resto son cuestiones de mejoras simplemente.

2022-02-17 23:35 UTC, federicomiranda commented
Ah, y a la duda que dejaste hoy... no, no es necesario cerrar el PR y abrir otro, mientras sigas pusheando a tu rama se va a actualizar este mismo PR 🙌🏼

2022-02-18 14:37 UTC, juliandebra commented
Hola Fede! Ahí cambié y borré algunas cositas que me dijiste. El CSS lo borré directamente y me agarré del archivo general. Cuando se hable sobre el diseño, tengamos una puesta en común como se van a encaminar los estilos y como se va a estructurar la organización de archivos, vuelvo a retomar el archivo CSS. Resolví lo de las funciones, no se si era la manera que vos pensabas, pero funciona! Vos me dirás que tal te parece.

2022-02-19 03:04 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +  const [errorMessage, setErrorMessage] = React.useState('');
Está mejor, pero se podría seguir optimizando. Cómo? En vez de tener muchos useState, podes tener uno solo que gestione toda esa info dentro de un objeto, y después usar spread operator para actualizar unicamente la key que necesites. Si lo probas, vas a ver que queda mucho más prolijo a la vista.

2022-02-19 03:06 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +  }
Idem a lo de arriba. La función está mucho mejor, pero puede ser mucho más óptima. Si convertis todos los useState a uno solo, y a esta función le pasas por parámetro cual es el slide que queres actualizar (puede ser con indices de array) vas a ver que esta función sería de como máximo 5 líneas. Porque vas a usar un solo setState que va a ser dinámico por índice.

2022-02-19 03:08 UTC, federicomiranda commented on src/Components/Home/HomeForm.jsx
> +        </form>
Esto también podría optimizarse más. Cómo? El onSubmit tal vez ni siquiera sea necesario, podes usar el onChange de los inputs para actualizar el estado, y al final tener un único botón que actualice toda la info junta después de ser cargada.

Y además de eso, tenes tres formularios que son iguales. Podrías cargar los datos que cambian en un array de objetos que tenga una key para el label, y otras keys para las cosas que cambian. Y después mapear ese array y te quedaría un solo bloque en vez de 3 o 4.

2022-02-21 18:28 UTC, juliandebra commented
Ahí modifiqué el código siguiendo los consejos que me dejaste. Me surgieron algunas dudas de como manejar el error  (que de hecho aún falta cerrar el manejo de los errores a la hora del submit), dentro de la cuestión UX. Pero supongo que se iran resolviendo una vez que tenga acceso a los datos provenientes del home (Mensaje de bienvenida, texto e imagenes). Si no se entiende a lo que me refiero, te lo comento bien en la daily.

2022-02-22 12:19 UTC, federicomiranda approved these changes
Tremendo cambio. La función se puede simplificar todavía más, pero la diferencia entre el inicio y este punto es abismal.

Para la próxima, tratar de hacer más commits específicos de cada parte de la tarea, así como mensajes de commit más claros y no tan genéricos como "home form".

2022-02-22 12:19 UTC, merged