Card created with styles
alkemyTech/OT144-CLIENT pull request #25
Opened 2022-02-24 02:33 UTC by juliandebra

### Componente Card

**Creado el componente card con los estilos puestos dentro de CardListStyles**
El componente recibe los props provenientes del parent desde el que se está trabajando. En caso de no recibir ningún valor, coloca elementos a modo de ejemplo. Como placeholder, encontramos el logo de la organización. 

**Estilos:** 
- Contiene una imagen de 250 x 250 (a discutir);
- El titulo todavía habría que testear con varias longitudes, en caso de que sea un titulo extenso, habría que hacerle un tratamiento parecido a la descripción;
- La descripción tiene un ellipsis en la 3 línea de texto. 

El componente está dentro de la carpeta utils, ya que como es un componente que se va a reutilizar en multiples componentes, deduje que era la carpeta indicada. Mientras que los estilos, los coloqué en el css de CardList para no hacer otro archivo aparte.

PD: cambié los tags de App.js en cada Route para que no generara conflicto con el mergeo de mi anterior PR. 

![image](https://user-images.githubusercontent.com/64337359/155445321-b35fbad8-93d8-4dab-b914-ab0555273041.png)

2022-02-26 04:08 UTC, federicomiranda requested changes
Corregir las cositas marcadas, y agregar las props que charlamos en la daily para poder pasarle links de facebook y linkedin.

Es un componente al que seguramente le tengamos que dar varias vueltas, sobre todo desde la parte visual.

2022-02-26 04:08 UTC, federicomiranda commented on src/Components/CardListStyles.css
> +}
Medio polémico el uso del asterisco. Sobre todo pensando en que el componente debería ser super reutilizable. Estamos seguros de que *siempre* va a tener un justify content center lo que esté adentro de card-container, y *siempre* va  atener un align-items center?

El box-sizing está bien aplicarlo a todos los elementos, pero debería estar definido en la hoja global de CSS, no en esta!

2022-02-26 04:08 UTC, federicomiranda commented on src/Components/CardListStyles.css
> +    overflow: hidden;
Es necesario el overflow? Para qué? Me hace un poco de ruido.

2022-02-26 04:08 UTC, federicomiranda commented on src/utils/Card.jsx
> +const Card = ({title, image, description}) => {
Antes de esta línea si agregaría un enter 😝

2022-02-26 04:08 UTC, federicomiranda commented on src/utils/Card.jsx
> +        <img src={'/images/SomosMas.png'} alt={title}/>}
Emprolijar un poquito más este ternario para que quede más legible:

```suggestion
        {
            image ? 
                <img src={image} alt={title} /> : 
                <img src={'/images/SomosMas.png'} alt={title} />
        }
```

2022-02-26 04:08 UTC, federicomiranda commented on src/utils/Card.jsx
> +        {title ? <h1>{title}</h1> : <h1>Titulo de prueba</h1>}
Este es de toc

```suggestion
        { title ? <h1>{title}</h1> : <h1>Titulo de prueba</h1> }
```

2022-02-26 04:08 UTC, federicomiranda commented on src/utils/Card.jsx
> +        <p>Descripción de prueba. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error facilis commodi illum? asdasdasdasdasdas dasdasdas</p>}
Y este si deberíamos emprolijarlo para mejorar la legibilidad

```suggestion
        {
            description ? 
                <p>{description}</p> : 
                <p>Descripción de prueba. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Error facilis commodi illum? asdasdasdasdasdas dasdasdas</p>
        }
```

2022-02-26 16:11 UTC, juliandebra commented on src/App.js
> +
🤦‍♂️

2022-02-26 16:12 UTC, juliandebra commented on src/Components/CardListStyles.css
> +    overflow: hidden;
Capaz no es la mejor práctica. Ahí lo limpié un poco al css de la descripción, pero si saco el overflow, muestra el texto entero, cuando lo que quiero es que si el texto supera los 3 (o 4 si se quiere) renglones, que me muestre los puntos suspensivos.

2022-02-26 21:10 UTC, federicomiranda requested changes
Corregir lo de la key del map, y ojo con el tema member. La card debería ser reutilizable para diferentes cosas, y con esa variable estás limitando el uso. Se tiene que poder usar para members, pero debería poder adaptarse fácilmente a cualquier otra cosa!

2022-02-26 21:10 UTC, federicomiranda commented on src/utils/Card.jsx
> +                <a href={member.linkedinUrl} key={i} >
Ojo, no es recomendable usar el indice como key en el map. React usa ese dato para optimizar el render y deberíamos garantizar que fuera un dato único e irrepetible de cada elemento (los índices no se repiten, pero los elementos de un array pueden cambiar de lugar y estarías cambiando el elemento que tenía x indice asignado)

Acá una lectura con más info al respecto: https://kentcdodds.com/blog/understanding-reacts-key-prop

2022-02-27 20:51 UTC, federicomiranda requested changes

2022-02-27 20:51 UTC, federicomiranda commented on src/utils/Card.jsx
> +        <>
El fragment no es necesario en este caso. No se si necesitas un contenedor a nivel estilos, pero a nivel react, no está cumpliendo ninguna función.

2022-02-27 20:51 UTC, federicomiranda commented on src/utils/Card.jsx
> +        }
Si la condición es renderizar una cosa o nada, lo que se hace es usar && en vez de un ternario:

condicion && <ComponenteARenderizarSiEsTrue />

2022-02-27 20:51 UTC, federicomiranda commented on src/utils/Card.jsx
> +        }
Idem

2022-02-27 20:55 UTC, federicomiranda commented
> Fede! Si bien me habías dicho que corrija lo del mapeo, me llevo eso para tener en cuenta (en este caso, debería haber puesto key={item.id} por si no entendí mal). Pero como dijo Braian, hablando por Slack, me pasó la siguiente imagen y me hizo dar cuenta de que debería imprimir cada item por separado. De todas formas, tengo que continuar viendo si es accesible a otros tipos de carta, a la hora de aplicarlo.
> 
> ![image](https://user-images.githubusercontent.com/64337359/155862995-f85e5a47-95da-4f1e-ae94-a10043eea4ec.png)

En cuanto de lo de la key, no importa que dato sea el que imprimas siempre y cuando sea único. Y en cuanto al resto de la data, no es responsabilidad de la card el mapeo, sino que lo que van a hacer es mapear la data y en cada vuelta generar una card pasandole los datos necesarios, así que en este caso no te tenes que preocupar vos, salvo que tengan que pasarle algún dato que no hayas contemplado.

2022-02-27 22:49 UTC, juliandebra commented on src/utils/Card.jsx
> +        <>
Sï, pensaba que lo iba a necesitar para estilizar y que tenga un flex direction: row para que esté un svg al lado del otro.  En este caso, tendría que ser section antes que fragment. A menos que haya otra manera.

2022-02-27 22:49 UTC, juliandebra commented on src/utils/Card.jsx
> +        }
Mala mía, ya me lo habías dicho encima. Ahora lo corrijo

2022-02-28 01:57 UTC, federicomiranda commented on src/utils/Card.jsx
> +        }
Indentar esto para que a simple vista se note que está adentro de la section y no a la misma altura!

2022-02-28 01:58 UTC, federicomiranda approved these changes
Ahora si, estamos ok

2022-02-28 01:58 UTC, federicomiranda commented on src/utils/Card.jsx
> +        <>
El fragment igual no te sirve para estilar, es un elemento que finalmente no se renderiza en el html. Si querés agregar un contenedor para estilos, si o si tiene que ser un tag válido de html.

2022-02-28 01:59 UTC, merged