Task: GetToken Method Security #OT144-69
alkemyTech/OT144-CLIENT pull request #26
Opened 2022-02-24 16:40 UTC by mgomez08

Enlace a la tarea [#OT144-69](https://alkemy-labs.atlassian.net/browse/OT144-69)

Se creó un método en el servicio de PrivateApi que obtiene el token almanenado en el localStorage y lo concatena a un string con la palabra Bearer.

2022-02-26 04:17 UTC, federicomiranda requested changes
Mínimo detalle, y si querés ya que estás tocando ese archivo al objeto config de abajo ya seteale 144 como Group!

2022-02-26 04:17 UTC, federicomiranda commented on src/Services/privateApiService.js
> +    const token = localStorage.getItem("token") || "";
Está bien, pero...

Hay un posible caso de uso en el que cuando la variable se setea en el local storage se haga mal y se termine seteando como undefined. Y te preguntaras "y qué? si undefined también va a dar false", y el problema es que el localstorage solo almacena texto, por lo cual no se va a guardar como *undefined* sino que se va a guardar como *"undefined"*. 

En base a ese caso de uso, habría que agregar esa otra validación!

2022-02-26 15:09 UTC, federicomiranda requested changes

2022-02-26 15:09 UTC, federicomiranda commented on src/Services/privateApiService.js
> +    if(token === "undefined") token = "";
Ojo, estás usando una constante y después en caso de ser "undefined" le estás reasignando un valor, eso se va a romper porque no se puede reasignar un valor a una constante. 

Buscaría mantener que sea una constante y validar todo en una línea!

2022-02-26 21:12 UTC, federicomiranda requested changes

2022-02-26 21:12 UTC, federicomiranda commented on src/Services/privateApiService.js
> +    : localStorage.getItem("token");
Y si es null? 😛 Te juro que no te estoy haciendo un chiste jajaja Reemplazaste la validación de null por la de "undefined", pero deberían estar las dos!

2022-02-27 00:00 UTC, mgomez08 commented on src/Services/privateApiService.js
> +    : localStorage.getItem("token");
Para no hacer otro commit fallido jajaja, el null sería el normal o el "null" string

2022-02-27 21:02 UTC, federicomiranda commented on src/Services/privateApiService.js
> +    || "";
Está perfecto, aunque podríamos buscar una forma más clara de escribirlo. Se me ocurre:

const ls_token = localStorage.getItem("token")
const token = ls && ls !== "undefined" ? ls : ""

2022-02-27 21:03 UTC, federicomiranda approved these changes
Ahora si, estamos ok. Igual te deje una recomendación para que sea un poco más legible!

2022-02-27 21:06 UTC, merged