[ADD] get request
alkemyTech/OT144-CLIENT pull request #29
Opened 2022-02-25 00:12 UTC by marsl27

Método get que recibe la url, el id, y el método getToken. Dentro del método se concatena la url y el id, con una barra en el medio. En el headers se manda el authorization que surge de ejecutar la función getToken.

2022-02-26 04:28 UTC, federicomiranda commented on src/Services/privateApiService.js
> +import { baseURL } from './Api';
Como que me robaste el nombre 😝 jajajaja

2022-02-26 04:29 UTC, federicomiranda commented on src/Services/privateApiService.js
> +        "Group": 144
Esas comillas no molestan, pero no son necesarias!

2022-02-26 04:32 UTC, federicomiranda requested changes
Más allá de los detalles mínimos marcados, no se si pediría como parámetro la función de getToken, como es siempre la misma, directamente la importaría en ese archivo y la usaría dentro de la función, sino vamos a estar obligando a todos que la importen por todos lados!

2022-02-26 04:32 UTC, federicomiranda commented on src/Services/privateApiService.js
> +export const getRequest =  async(url,getToken,id = null) =>{
Me mata el toc, necesito espacios

```suggestion
export const getRequest =  async (url, getToken, id = null) => {
```

2022-02-26 04:32 UTC, federicomiranda commented on src/Services/privateApiService.js
> +            url: id===null ?`${baseURL}${url}` : `${baseURL}${url}/${id}`,
```suggestion
            url: id === null ? `${baseURL}${url}` : `${baseURL}${url}/${id}`,
```

2022-02-26 04:32 UTC, federicomiranda commented on src/Services/privateApiService.js
> +                'Authorization':getToken(),
```suggestion
                'Authorization': getToken(),
```

2022-02-26 15:24 UTC, marsl27 commented
> Ojo, sacaste el getToken de los parámetros de la función y eso está perfecto. Pero ahora estás ejecutando esa función y no está definida en ningún lado. Te falta importarla al principio del archivo!

Por lo que entiendo, la función va a estar en el mismo archivo cuando se haga merge de lo que hizo Marlon. Por eso lo saque de los parámetros, porque la usa directo del mismo archivo. No se si estoy en lo cierto.

2022-02-26 21:18 UTC, federicomiranda requested changes
Verdad. Mala mía jajaja

Está perfecto, ahí te hice una única corrección mínima y estamos para mergear!

2022-02-26 21:18 UTC, federicomiranda commented on src/Services/privateApiService.js
> +        let response = await axios({
Si response después no va a cambiar su valor debería ser una constante!

2022-02-27 21:15 UTC, federicomiranda commented on src/Services/privateApiService.js
> +            url: id === null ? `${baseURL}${url}` : `${baseURL}${url}/${id}`,
Está perfecto, dejo un comentario de algo que mejoraría:

Igualar a null no tiene sentido en este caso porque null, undefined, o cualquier valor falsy deberíamos tomarlo de la misma manera, por lo cual optaría por hacer la condición como !id

2022-02-27 21:16 UTC, federicomiranda approved these changes
Ahora si, perfecto

2022-02-27 21:16 UTC, merged