Task/register form
alkemyTech/OT144-CLIENT pull request #3
Opened 2022-02-17 23:27 UTC by gfalotico

Styling remains to be done, but the logic is finished.

2022-02-18 00:02 UTC, federicomiranda commented on src/Components/Auth/RegisterForm.js
> +            validate: value => {
Si bien no se pedía en el ticket, es super importante, sobre todo en este formulario, que podamos validar el email.

2022-02-18 00:04 UTC, federicomiranda commented on src/Components/Auth/RegisterForm.js
> +                        <>
Cada vez que se usa un map es super importante asignarle una key a los elementos, ayuda a que react pueda hacer más óptimo el proceso de renderizado.

2022-02-18 00:05 UTC, federicomiranda requested changes
Muy bien, solo dos detalles.

2022-02-18 00:05 UTC, federicomiranda commented
Más allá de las correcciones estrictamente de código siempre está bueno que en el detalle de las PRs podamos explicar más sobre lo que hicimos, algún punteo o dar más contexto de las tareas, porque muchas veces la persona que nos va a corregir el código no tiene idea de lo que estamos haciendo.

2022-02-18 00:07 UTC, gfalotico commented on src/Components/Auth/RegisterForm.js
> +            validate: value => {
Dale, pensé q la validación del input era suficiente.

2022-02-18 00:09 UTC, gfalotico commented on src/Components/Auth/RegisterForm.js
> +                        <>
El input tiene una key, el error como todavía no tiene un componente definido creo q no hace falta q le ponga una key. No sabría donde agregarla.

2022-02-18 00:11 UTC, gfalotico commented
Si tenes razón, estaba viendo como lo hizo Marlon y me di cuenta que mínimamente hace falta linkear la Task paga agilizar el proceso de corrección. Lo voy a tener en cuenta para las próximas pull requests.

2022-02-19 03:15 UTC, federicomiranda requested changes
El cambio del email está ok. Lo que pasa con la key en el input, es que no debería tenerla el input. Deberías convertir ese fragment que hoy tenes como <></> en un <React.Fragment></React.Fragment> y agregarle la key a ese elemento!

2022-02-22 12:25 UTC, federicomiranda approved these changes
Bien. Super prolijo. Para la próxima mejorar la presentación general del PR.

2022-02-22 12:25 UTC, merged