Task/metodo reutilizable peticion put
alkemyTech/OT144-CLIENT pull request #32
Opened 2022-02-26 15:23 UTC by EstebanAbella

Método reutilizable petición PUT

- **Recibe por parámetro:**

1. ruta destino (endpoint)
2. identificador (id)
3. objeto para enviar en el BODY (body)

- **Por Headers:**

1. Authorization en base al token del usuario

2022-02-28 02:03 UTC, federicomiranda requested changes
Está perfecto, hay que corregir esos detalles que te los dejé todos como suggestions así que podes aceptarlos desde github para que se commiteen sin que tengas que meter mano en el código y pushear!

2022-02-28 02:03 UTC, federicomiranda commented on src/Services/privateApiService.js
> +export const PutRequest = async(endpoint,id,body) => {
El nombre de la función debería empezar con minúscula, y no le tengas miedo a los espacios jajaja

```suggestion
export const putRequest = async (endpoint, id, body) => {
```

2022-02-28 02:03 UTC, federicomiranda commented on src/Services/privateApiService.js
> +        let res = await axios({
Si después res no modifica su valor debería ser una constante, y en el método get se usa response como nombre, así que respetemos esa nomenclatura:

```suggestion
        const response = await axios({
```

2022-02-28 02:03 UTC, federicomiranda commented on src/Services/privateApiService.js
> +                'Authorization':getToken(),
```suggestion
                'Authorization': getToken(),
```

2022-03-01 17:07 UTC, marsl27 commented on src/Services/privateApiService.js
> +            body: body,
El método no me funcionaba. Me decía que el campo nombre es requerido a pesar de que se lo estaba mandando. Es decir, no estaba recibiendo el body. Lo que tuve que hacer fue cambiar la palabra "body" por la palabra "data" en este método para que me funcione. O sea me quedó: data: body. Fijate si te funciona, sino hoy lo hablamos en la daily.

2022-03-01 18:16 UTC, federicomiranda approved these changes
Perfecto!

2022-03-01 18:18 UTC, merged