Member list table with styles from Esteban's PR created
alkemyTech/OT144-CLIENT pull request #37
Opened 2022-02-27 17:39 UTC by juliandebra

### Tabla de Lista de Miembos

Creé una tabla siguiendo la mismas lógicas que Mariel y Esteban, para que de esa forma tengan coherencia entre todas las tablas. También tomé los éstilos del PR de esteban. No modifiqué nada de los estilos, ya que creo que es mejor que se mergeen para poder editarlos y así no generar conflictos.  

En la task decia que había que mockear los valores. Esto mismo lo hice desde un axios GET, que luego de globalizar los métodos axios, se borrará para reemplazarlo con las funciones que corresponde (el console.log() también se va😛) . De igual manera para las funciones de Edit y Delete.

![image](https://user-images.githubusercontent.com/64337359/155893019-86cd11de-d970-4dd5-a86e-a8cb69538ca9.png)

2022-02-28 02:21 UTC, federicomiranda requested changes
Detalles!

2022-02-28 02:21 UTC, federicomiranda commented on src/Components/Members/MemberList.jsx
> +    }, [])
Mockear los contenidos es poner texto falso jajaja Esto saquemoslo ahora y pongamos texto falso para no generar conflictos después

2022-02-28 02:21 UTC, federicomiranda commented on src/Components/Members/MemberList.jsx
> +    const editMember = () => {}
Charlen para ponerse de acuerdo en el nombre de las funciones, Mariel y Esteban usaron otra nomenclatura!

2022-02-28 02:31 UTC, juliandebra commented on src/Components/Members/MemberList.jsx
> +    }, [])
Sí, pensaba que lo que hice fue una especie de mockeado, pero se ve que lo llevé muy lejos jajaja. O sea, ¿Tendría que reemplazar {member.name} por "Juan Perez" o lo que se me ocurra y que eso despues se modifique en una tarea futura o creo un objeto con varios values para despues mapearlo?

2022-03-01 18:27 UTC, federicomiranda commented on src/Components/Members/MemberList.jsx
> +    }, [])
No, metes el Juan Perez así nomás jajaja

2022-03-01 18:28 UTC, federicomiranda approved these changes
Ahora si!

2022-03-01 18:29 UTC, merged