Delete request for privateApiService
alkemyTech/OT144-CLIENT pull request #41
Opened 2022-02-28 02:15 UTC by juliandebra

**Agrego la función deleteRequest en privateApiService.**

Toma la url y el id. En caso de que requiera un id hace la operación ternaria. Traté de quede coherente con la sintaxis de Mariel y Galo para que quede mas prolijo. Tengo mis dudas aún, acerca de su aplicación.

2022-02-28 02:36 UTC, federicomiranda requested changes
Ese detalle, el resto está muy bien

2022-02-28 02:36 UTC, federicomiranda commented on src/Services/privateApiService.js
> +            url: id ? `${baseURL}/${url}` : `${baseURL}/${url}/${id}`,
Ojo, en un caso de delete, el id no es un dato optativo porque si no se lo pasas que pasa? La api que borra? Todo? Jajajaja

Así que acá deberías tomar el id como parámetro obligatorio y la url sería directamente la que tiene el id, sin operador ternario!

2022-02-28 02:49 UTC, juliandebra commented on src/Services/privateApiService.js
> +            url: id ? `${baseURL}/${url}` : `${baseURL}/${url}/${id}`,
Ahí revisé bien la api, y si, todos necesitan id. No me había dado cuenta. Ahí commiteé 😄

2022-03-01 18:36 UTC, federicomiranda approved these changes
Ahora si!

2022-03-01 18:37 UTC, merged