CardContainer and cards
alkemyTech/OT144-CLIENT pull request #43
Opened 2022-02-28 21:23 UTC by gfalotico

[OT144-56](https://alkemy-labs.atlassian.net/browse/OT144-56)
### Features

- The home file was created, which would be the index of "What's New".  
- The "ArticleCard" component was created to render the news dynamically with its respective css file.
- The title of the article will occupy the whole container only in mobile views and in normal views a part of it in order to limit the number of words.
- Article images will have a maximum height of 300px.
- The size of the cards will be 400px.
- Paragraphs will have a maximum of 4 rows.

### Details

- A date converter has not been defined because it has not yet been defined how these dates will be displayed.
- A test object has been uploaded because the requests to obtain the news have not yet been created.

2022-02-28 22:31 UTC, Braifz commented on src/Components/News/Home.js
> +          <ArticleCard  index={index} data={data}/>
Acá tal vez estaría bueno utilizar la Card hecha por @juliandebra...
Link a [Card](https://github.com/alkemyTech/OT144-CLIENT/pull/25)

2022-03-01 18:53 UTC, federicomiranda requested changes
Me sumo al comentario de @Braifz, aprovechemos el componente de card que armó @juliandebra y si necesitamos algún cambio en ese componente para que se adapte al caso de uso, pedirle los cambios necesarios!

2022-03-01 20:23 UTC, gfalotico commented
> Me sumo al comentario de @Braifz, aprovechemos el componente de card que armó @juliandebra y si necesitamos algún cambio en ese componente para que se adapte al caso de uso, pedirle los cambios necesarios!

yo busque para haber si habia algun componente para poder reutilizar y no encontre nada. Para dejar de perder el tiempo yo armaria una carpeta de componentes donde sea facil de identificarlos. Para asi no hacer dos veces las mismas cosas.

2022-03-01 21:59 UTC, federicomiranda commented on src/Components/News/Home.js
> +            key={index}
No es una buena práctica usar el index como key. Es mejor que no pasar nada, pero sigue sin ser lo más eficiente. Las keys que se pasan a cada elemento que mapeamos debería ser un valor siempre único de ese elemento, un id, la concatenación de dos datos, o cualquier cosa, no importa lo que sea, solo que sea único.

Al poder cambiar el orden del array o agregar nuevos elementos al comienzo, el indice de los elementos puede variar y el que hoy es 0 mañana puede ser 2. React usa la key para optimizar el render de los elementos de las listas, y para un mejor funcionamiento es necesario que sean valores únicos.

2022-03-01 22:02 UTC, federicomiranda approved these changes
Ahí está perfecto.

Sobre lo de la card, está perfecta la iniciativa de búsqueda. Pero siempre recomiendo que vean las tareas que tienen que hacer sus compañeros, y las dailies sirven para que todos estemos al tanto de que están haciendo las otras personas. Si vos sabes que existe un componente card, aunque no lo encuentres en el proyecto sabes que está y podes preguntar.

SI no estamos de acuerdo con que el componente esté en la carpeta utils, eso se puede discutir y seleccionar un lugar mejor dentro del proyecto para que sea más fácil para todo el equipo.

2022-03-01 22:04 UTC, merged