Task/user requests
alkemyTech/OT144-CLIENT pull request #57
Opened 2022-03-02 19:46 UTC by gfalotico

[OT144-78](https://alkemy-labs.atlassian.net/browse/OT144-78)
### Features

- Se creo el  archivo userSerivice.js dentro de services para poder hacer los llamados correspondientes
- Se conecto el servicio con usersList

2022-03-02 22:22 UTC, federicomiranda commented on src/Components/Users/UsersList/UsersList.js
> +  }, []);
Esto no era necesario en esta instancia pero está ok

2022-03-02 22:23 UTC, federicomiranda requested changes

2022-03-02 22:23 UTC, federicomiranda commented on src/Services/userService.js
> +}*/
Que pasó que esto está comentado?

2022-03-02 23:46 UTC, gfalotico commented on src/Services/userService.js
> +}*/
Lo deje comentado porque como no estaba subida la postRequest me tiraba error. Me olvide de descomentarla porque la branch main ya tiene es funcion.

2022-03-02 23:48 UTC, gfalotico commented on src/Components/Users/UsersList/UsersList.js
> +  }, []);
Es que según leí, decía conectar el service con users pero después hablando con @juliandebra me dijo que no hacia falta.

2022-03-03 00:32 UTC, juliandebra commented on src/Services/userService.js
> +}*/
Si, eso directamente borralo, total despues va a cambiar por las funciones de extensión.

2022-03-03 21:46 UTC, federicomiranda commented
@gfalotico @juliandebra me perdí un poco acá, cómo quedamos? Avisenme ustedes así podems cerrar este PR!

2022-03-04 01:11 UTC, gfalotico commented
> @gfalotico @juliandebra me perdí un poco acá, cómo quedamos? Avisenme ustedes así podems cerrar este PR!

En resumen, solo habria que descomentar la funcion y listo. Ahora lo hago asi ya se puede hacer el pull

2022-03-05 02:30 UTC, federicomiranda approved these changes
Perfecto, avanzamos

2022-03-05 02:31 UTC, merged