Task/env endpoints contacts
alkemyTech/OT144-CLIENT pull request #59
Opened 2022-03-03 12:20 UTC by marsl27

Se agrega archivo .env.example con la variable de entorno correspondiente al endpoint de contactos. Se elimina la ultima barra de la url base para que la misma se agregue en cada uno de los endpoints. Se corrigen bugs de las rutas correspondientes a los componentes de card y table.

2022-03-03 15:57 UTC, Braifz commented on src/Components/Contact/ServiceAPIContact.js
>    await putRequest("contacts", id, body);
A updateContact quedo sin agregar la variable de entorno :P

2022-03-03 21:49 UTC, federicomiranda requested changes

2022-03-03 21:49 UTC, federicomiranda commented on .env.example
> +REACT_APP_URL_CONTACTS = /contacts
Quitar espacios y agregar comillas para anular el margen de error:

```suggestion
REACT_APP_URL_CONTACTS="/contacts"
```

2022-03-03 21:49 UTC, federicomiranda commented on package.json
> +    "dotenv": "^16.0.0",
Eliminar la librería que no se usa!

2022-03-03 21:49 UTC, federicomiranda commented on src/Components/Contact/ServiceAPIContact.js
>    await putRequest("contacts", id, body);
Esto ⬆️

2022-03-05 02:33 UTC, federicomiranda requested changes

2022-03-05 02:33 UTC, federicomiranda commented on src/Components/Contact/Contact.js
> +  }, [])
Habíamos acordado el uso de async await. De todas formas, para la vida, cada vez que uses un then es muy importante que uses un catch!

2022-03-05 16:19 UTC, marsl27 commented on src/Components/Contact/Contact.js
> +  }, [])
Si, me quedo a medio hacer porque como me iba a trabajar, hice push para poder seguirlo desde otra compu. De todas formas lo voy a borrar porque ayer quedamos en que las conexiones http las hacíamos cada uno sobre el componente que nos tocó el reducer y a mi me tocó novedades.

2022-03-06 02:02 UTC, federicomiranda approved these changes

2022-03-06 02:02 UTC, merged