[ADD] newsReducer with types and actions. Conection news component wi…
alkemyTech/OT144-CLIENT pull request #73
Opened 2022-03-06 16:51 UTC by marsl27

![image](https://user-images.githubusercontent.com/69442124/156932990-e4d8f9d8-4d64-4986-a080-bc31f7265462.png)

Cree la función newsReducer con su correspondiente estado inicial. El mismo tiene las acciones de crear, editar, borrar y traer todas, que se importan del archivo de acciones. Agregué los tipos que se utilizan al archivo types.

Pasé los servicios http de news a la carpeta de services.

Conecté el newsReducer al rootReducer.

Conecté los servicios http al componente novedades del backoffice.

2022-03-07 04:12 UTC, federicomiranda requested changes
En general está super bien, hay algunos detalles para corregir!

2022-03-07 04:12 UTC, federicomiranda commented on src/App.js
> +import React, { useEffect } from 'react';
Eliminar ese import de useEffect, no se usa para nada 👀

2022-03-07 04:12 UTC, federicomiranda commented on src/Components/Home/BackOffice/Novedades.js
> +            //Alert setNews failed
Agregar acá (y en los demás) el componente de alerta que ya está mergeado a main!

2022-03-07 04:12 UTC, federicomiranda commented on src/Components/Home/BackOffice/Novedades.js
> +            })()
Bien ahí esa IIFE

2022-03-07 04:12 UTC, federicomiranda commented on src/reducers/newsReducer.js
> +    console.log(action);
Eliminar este console log para que no llegue a main!

2022-03-07 04:12 UTC, federicomiranda commented on src/reducers/newsReducer.js
> +                 action.payload : elem)}
Está probado esto? Me hace un poco de ruido 🤔

2022-03-07 11:54 UTC, marsl27 commented on src/Components/Home/BackOffice/Novedades.js
> +            //Alert setNews failed
No lo agregué porque no me toca sobre este componente.

2022-03-07 11:58 UTC, marsl27 commented on src/reducers/newsReducer.js
> +                 action.payload : elem)}
Si si, está probado y funcionó.

2022-03-08 01:20 UTC, federicomiranda approved these changes
Vamos nomas

2022-03-08 01:20 UTC, merged