OT144-109
alkemyTech/OT144-CLIENT pull request #77
Opened 2022-03-06 20:40 UTC by gfalotico

[OT144-109](https://alkemy-labs.atlassian.net/browse/OT144-109)
### Features

- Se genero archivos llamados "categories" en las Carpetas Reducers y Actions. Donde se establecen ambos para que funcionen en la store. 
- Se agrego en Types los tipos de llamados que se realizan

2022-03-07 04:22 UTC, federicomiranda requested changes

2022-03-07 04:22 UTC, federicomiranda commented on src/Services/categoriesService.js
> +const endPoint = '/categories';
Acá habría que usar la variable de entorno creada!

2022-03-07 04:22 UTC, federicomiranda commented on src/reducers/categories.js
> +  console.log(action);
Eliminar este console log para que no llegue a main

2022-03-07 04:22 UTC, federicomiranda commented on src/reducers/categories.js
> +      console.log("default");
Idem!

2022-03-07 04:22 UTC, federicomiranda commented on src/reducers/categories.js
> +      };
Está probado este método?

2022-03-07 04:22 UTC, federicomiranda commented on src/actions/categories.js
> +};
Este archivo es un poco sobreingeniería. No es 100% necesario, y en caso de mantenerlo, que tampoco está mal, creo que sería más adecuado tenerlo en utils que en actions. Porque las actions son de redux, y eso son funciones que no tienen relación con redux más allá de dispatchar algo

2022-03-07 20:21 UTC, gfalotico commented on src/reducers/categories.js
> +  console.log(action);
Error de novato :)

2022-03-07 20:22 UTC, gfalotico commented on src/reducers/categories.js
> +      };
con esos valores no, pero logicamente si

2022-03-07 20:24 UTC, gfalotico commented on src/actions/categories.js
> +};
Esto es donde tenia dudas, hoy en la daily lo podemos charlar con los demas para ver como se estableció. Porque las pocas veces que trabaje con redux el actions se solia usar asi pero no con la forma del archivo actions.

2022-03-07 20:27 UTC, gfalotico commented on src/reducers/categories.js
> +      };
https://replit.com/join/opkcoapfdd-gfalotico88

2022-03-07 20:30 UTC, gfalotico commented on src/reducers/categories.js
> +      };
ya me di cuenta, tiene que estar al revés

2022-03-07 20:32 UTC, gfalotico commented on src/reducers/categories.js
> +      };
Me pasa por confiar en el codigo sin probarlo

2022-03-08 01:36 UTC, federicomiranda commented on src/reducers/categories.js
> +  console.log(action);
No pasa nada, para eso estamos jajaja

2022-03-08 01:38 UTC, federicomiranda commented on src/reducers/categories.js
> +      };
Bingo! Jajajaja

2022-03-08 01:41 UTC, federicomiranda commented on src/actions/categories.js
> +};
Por ahora lo podemos dejar acá para no entorpecer, pero recomiendo mover!

2022-03-08 01:46 UTC, federicomiranda approved these changes
Perfecto

2022-03-08 01:47 UTC, merged