Task: Create and edit user
alkemyTech/OT144-CLIENT pull request #8
Opened 2022-02-21 15:28 UTC by juliandebra

**Crear o editar usuario existente**

Tareas realizadas: 
- Modifiqué el archivo UserForm.js, integrando la librería de Formik. Agregué el campo de contraseña y el upload para la foto de perfil.  
- Escribí las validaciones de las funciones en un archivo aparte para que el código de UserForm esté mas limpio. Estas funciones lo que hace es activar el error de Formik, cuando el campo es requerido y no hay información dentro o cuando la información colocada es invalida.  
- Coloqué como constante los formatos permitidos para el upload. 
- Creé un componente donde te da un preview de la imagen. 
- Utilicé Axios (get, post y patch) para obtener (en caso de ser existente) el usuario y en el momento del Submit, actualizar o crear los datos del usuario.

Aún por corregir: 
- No están colocados los estilos.
- El preview de la imagen (en caso de que sea un usuario nuevo o sin imagen) podría ya tener una imagen estandarizada como el logo de User  en escala de gris. 
- Queda por definir el método con el que se recibe el user o el user.id para que de esa manera se corrobore la existencia de tal registro.
- Una vez que el método este definido, dentro de axios.post y axios.patch, se debe actualizar los registros del usuario.
- Cuando estoy en modo responsive (dentro del Chrome) el Select Field no registra el onChange, pero cuando estoy modo escritorio (modo normal), anda bien. 

![create user 1](https://user-images.githubusercontent.com/64337359/154981839-05bb9893-5961-480a-aa71-c19f3b48d715.png)
![create user 2](https://user-images.githubusercontent.com/64337359/154981840-dbcaf745-87f7-4bbf-a893-ffa23d8a923e.png)
![create user 3](https://user-images.githubusercontent.com/64337359/154981844-3ee62def-d694-40f3-8df7-b616ad53afc8.png)

2022-02-21 17:29 UTC, juliandebra commented
Acabo de notar que poniendo "accept" en la linea del upload no basta para que el usuario evite subir otros formatos. Me faltaría agregar una función nueva para que de error en caso de subir un archivo en otro formato.

2022-02-22 13:01 UTC, federicomiranda commented on src/Components/Users/UsersForm.js
> +                    <Field className="input-field" type="text" name="name" value={values.name || ''}
En estos inputs no es necesario el OR '' porque los values arrancan con un estado inicial vacío para cada key. Así que es vacío o el valor que tengan.

2022-02-22 13:03 UTC, federicomiranda requested changes
El accept debería ser suficiente, probá con los valores: image/png, image/jpeg

El resto está muy bien, solo corregir ese detalle de los values que te mencioné para que no nos quede basura en el código.

El PR está increíble, el nivel de detalle es buenísimo, solamente faltaría linkear la tarea que corresponde en jira y sería perfecto. Pero super bien!

2022-02-23 02:03 UTC, federicomiranda approved these changes
Perfecto

2022-02-23 02:03 UTC, merged