Task/contact alert
alkemyTech/OT144-CLIENT pull request #80
Opened 2022-03-07 15:17 UTC by juliandebra

### Alertas para las peticiones de Contacto

Coloqué un try & catch para las peticiones de contacto. En caso de agarrar el error, setea el estado error para mostrar el alerta.
Todavía faltan los atributos de BasicAlert, pero al igual que el otro PR, quisiera saber si está encaminado.

2022-03-08 02:06 UTC, federicomiranda requested changes

2022-03-08 02:06 UTC, federicomiranda commented on src/Components/Contact/Contact.js
> +  }, []);
Acá habría que implementar async await

2022-03-08 02:06 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +    }
Implementar async await y eliminar el comentario!

2022-03-08 21:57 UTC, federicomiranda requested changes

2022-03-08 21:57 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +      })()
Esto no es necesario. La función ContactForm debería ser async y solamente tener el const response con el await, la IIFE no aporta en este caso

2022-03-08 22:04 UTC, juliandebra commented on src/Components/Contact/ContactForm.js
> +      })()
Ahí lo corregí!

2022-03-09 02:31 UTC, federicomiranda approved these changes
Ahora si, pero ojo. Guardas la respuesta en la constante de response, y que haces con eso? En este momento nada, por lo cual no sabes si salió todo bien o no, y el usuario tampoco se entera.

2022-03-09 02:32 UTC, merged

2022-03-09 04:31 UTC, juliandebra commented
Claro, en caso de concretar la petición deberia mostrar un alert de success, o un console.log(response.data). Pero no estaba seguro de como proceder con esa tarea o si es para una task a futuro.