[ADD] alert component and spinner in activities and activityDetail
alkemyTech/OT144-CLIENT pull request #83
Opened 2022-03-08 02:32 UTC by marsl27

Agregué lo siguiente en Actividades.js y activitiesDetail.js:
- Un estado que contiene un objeto con el loading, la data y el error.
- Un useEffect que llama al get y setea la data y el loading en false en caso de retornar un status 200. Caso contrario setea el mensaje de error y el loading en false.
- En el return, si el loading es true, renderiza el spinner. Si el error tiene texto, renderiza la alerta de error. Y sino, renderiza la data obtenida.

2022-03-08 22:01 UTC, federicomiranda commented
Revisar los conflictos!

2022-03-09 02:37 UTC, federicomiranda commented on src/Components/Activities/Actividades.js
> +        response.status === 200 ? setDataLoading({ ...dataLoading, data: response.data.data, loading: false }) : setDataLoading({ ...dataLoading, error: response.error, loading: false })
No hacer un ternario con tanta info, es preferible un if tradicional, se va a entender mejor

2022-03-09 02:38 UTC, federicomiranda commented on src/Components/Activities/Actividades.js
> +          <ErrorAlert />
Y acá algo parecido. Si bien esto funciona, la mejor práctica para que sea todo claro es sacar esas condiciones a algunos if por encima del return

if (dataLoading.loadin) {
   return <Spinner />
}

if (dataLoading.error) {
    retirm <Error />
}

2022-03-09 02:40 UTC, federicomiranda requested changes

2022-03-09 02:40 UTC, federicomiranda commented on src/Services/ServiceAPIActividades.js
> +>>>>>>> 6d071b5c87adc64dee6e0409cb480e628b3e737c:src/Services/ServiceAPIActividades.js
Quedó lleno de conflictos este archivo!

2022-03-09 21:18 UTC, federicomiranda commented
Siguen estando los errores marcados y hay conflictos

2022-03-09 21:22 UTC, marsl27 commented
Fede, lo de los if lo corregi. Y los conflictos, cuando lo pushee no tenia ninguno y la aplicacion funcionaba. Debe ser que al mergear los otros PR aparecen nuevos conflictos. Mas tarde lo reviso.

2022-03-09 23:29 UTC, marsl27 commented
Fede, ahi vi los conflictos. Lo que pasa es que borre el archivo http-news porque los servicios de news estan en NewsApiServices, por lo que estaba repetido. Puede ser que al querer mergear, salte como que ese archivo sigue estando en main. Lo borré nuevamente y corregi los imports. Ademas, agregue el servicio get al home de las news porque solo estaba en el back office.

2022-03-11 00:38 UTC, federicomiranda approved these changes
Ahora si!

2022-03-11 00:39 UTC, merged