Task/activities redux
alkemyTech/OT144-CLIENT pull request #87
Opened 2022-03-08 23:55 UTC by juliandebra

### Reducer para el componente Activities

- Types creados en carpeta types;
- Agregada las actions de activities;
- Reducer de Activities Creado;
- Reducer incorporado en rootReducer
- Métodos conectados al componente Activities.js
- ActivitiesList.js conectado al componente Activities.js (Esto podría no ir)

Traté de respetar los nombres de funciones y paths del PR  #83 que hizo @marsl27  con respecto a las modificaciones en cuanto a las peticiones y a sus respectivos endpoints. También modifiqué el App.js en relación a lo que hizo Mariel, para evitar que haya la menor cantidad de conflictos. De todas formas, si es que se generan conflictos, agrego las funciones del PR mencionado anteriormente, ya que puede que no se levante la App por no poder encontrar dichas funciones.

2022-03-09 04:28 UTC, juliandebra commented
Ya había conflictos en el mismo PR y se me pasaron de largo. Estuve hasta recién viendo como resolverlos y lo tuve que hacer manualmente porque por github no me dejaba.
Agregue una corrección de la task contact-alert, ya que noté que había que volver a poner async para que pueda recurrir al await dentro del try. Si queda desordenado corregirlo por aca por mas que sea algo chiquito, ya la próxima se que tengo que abrir otro PR aparte.

2022-03-09 21:21 UTC, federicomiranda requested changes
Detalle

2022-03-09 21:21 UTC, federicomiranda commented on src/Components/Activities/Activities.js
> +        })()
No es necesaria la IIFE, ya estás adentro de una función, solo hay que volver a la función async

2022-03-09 21:21 UTC, federicomiranda commented on src/Components/Activities/Activities.js
> +          })()
No es necesaria la IIFE, ya estás adentro de una función, solo hay que volver a la función async

2022-03-09 21:21 UTC, federicomiranda commented on src/Components/Activities/Activities.js
> +          })()
No es necesaria la IIFE, ya estás adentro de una función, solo hay que volver a la función async

2022-03-11 00:40 UTC, federicomiranda commented
Se generaron unos conflictos, seguramente a partir del último merge, revisar porfa!

2022-03-11 17:32 UTC, juliandebra commented
Conflictos resueltos!

2022-03-13 05:11 UTC, federicomiranda approved these changes
Vamos nomas

2022-03-13 05:11 UTC, merged