Task/reducer slider
alkemyTech/OT144-CLIENT pull request #91
Opened 2022-03-10 03:48 UTC by Braifz

Tarea asignada: [#OT144-110](https://alkemy-labs.atlassian.net/browse/OT144-110)

Tareas realizadas :
- Se creo reducer para gestionar el estado de los Sliders.
- Peticiones de la API se almaceno en el reducer.

2022-03-10 03:50 UTC, Braifz commented
El primer commit es lo mismo que esta en la PR de [[fix some bugs]](https://github.com/alkemyTech/OT144-CLIENT/pull/90), y a partir de eso cree esta rama para poder trabajar sin errores.

2022-03-11 00:55 UTC, federicomiranda requested changes
El reducer está bien, pero entraron esos cambios que no deberían estar y hay que corregir!

2022-03-11 00:55 UTC, federicomiranda commented on src/Components/Contact/Contact.js
> +          Phone: <span> {phone} </span>{" "}
Eliminar esos espacios (es el problema de tener dos commits iguales en diferentes PRs jajaja)

2022-03-11 00:55 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +          ) : null}
Misma corrección que en el otro PR, usar el && en vez de ternario

2022-03-11 00:55 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +          ) : null}
Idem

2022-03-11 00:55 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +          ) : null}
Idem

2022-03-11 00:55 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +          ) : null}
Idem

2022-03-11 00:55 UTC, federicomiranda commented on src/Components/Home/BackOffice/Novedades.js
> +        setError(true);
Por qué cambió el dispatch por un setstate?

2022-03-11 02:10 UTC, Braifz commented on src/Components/Contact/Contact.js
> +          Phone: <span> {phone} </span>{" "}
:C

2022-03-11 04:35 UTC, closed without merging