Task/componente header backoffice
alkemyTech/OT144-CLIENT pull request #92
Opened 2022-03-10 19:45 UTC by EstebanAbella

**Componente header backoffice**

Se creo el componente Header
Se creo una primera aproximación del navegador responsive
Al adaptarse a tamaño para tablet aparece el menu-btn
El menu-btn contrae y expande un sidebar con el nombre de la ONG
El componente Header es renderizado por el componente HomePage

Esto es una primera aproximación sujeta a posibles cambios, el ticket solo pedía realizar el menu-btn pero me entusiasme

2022-03-11 01:02 UTC, federicomiranda requested changes
En general está bien, solo algunos pequeños cambios

2022-03-11 01:02 UTC, federicomiranda commented on src/Components/Contact/ContactForm.js
> +      const response = postContact(data);
Esto debería tener el await, la otra acción es síncrona

2022-03-11 01:02 UTC, federicomiranda commented on src/Components/Home/BackOffice/HeaderComponent.js
> +  }
Si tiene dos estados usar true y false en lugar de strings

2022-03-11 01:02 UTC, federicomiranda commented on src/Components/Home/BackOffice/stylesLogo.css
> +    height: auto;
El height es auto por default. Y hay un componente reutilizable de imagenes con lazy load

2022-03-11 02:36 UTC, EstebanAbella commented on src/Components/Home/BackOffice/HeaderComponent.js
> +  }
Ahí estoy usando el hook 'btnResponsive' como clase del navegador y sidebar para contraerlo y expandirlo al hacer click en el btn-menu, hay alguna práctica mejor para realizar esta acción?
De igual modo hay otro ticket que pide realizar un componente sidebar por lo cual este se eliminaría, y ahí si puedo poner true o false en los estados del hook 'btnResponsive' para luego pasarlo por props al componente sidebar desde el componente 'HeaderCompont'.

2022-03-13 05:29 UTC, federicomiranda approved these changes
Bien!

2022-03-13 05:30 UTC, merged