Task/public header
alkemyTech/OT144-CLIENT pull request #98
Opened 2022-03-11 23:04 UTC by marsl27

Se creó el componente PublicHeader. En el mismo se agregó el logo "Somos más", el nav con los enlaces y los botones de iniciar sesión y registrarse. Además se creó la ruta activa cuando la misma se encuentra seleccionada.

2022-03-12 12:01 UTC, juliandebra reviewed
Comentario acerca de novedades.js

2022-03-13 05:40 UTC, federicomiranda commented
Los archivos de novedades no deberían estar dentro de este pr. Igualmente ese archivo está generando demasiados conflictos, porfa hablen con @juliandebra y si no me equivoco @EstebanAbella que también los tocaron así se encarga una sola persona de dejarlo andando!

2022-03-13 05:42 UTC, federicomiranda requested changes

2022-03-13 05:42 UTC, federicomiranda commented on src/Components/Layout/Header/PublicHeader.jsx
> +                            <li key={index} id={dato.url === window.location.pathname ? "activePath" : null}>
No es buena práctica usar el index como key dentro de un map. Podes hacer una composición de dato.nombre + index o algo por el estilo que genere un id realmente único!

2022-03-13 05:42 UTC, federicomiranda commented on src/Components/Layout/Header/PublicHeader.jsx
> +                        return (
Acá podes evitar el return si a la función en vez de llavez le pones paréntesis. 

datos.map((dato, index) => ( <ComponenteRetornado /> ))

Algo así

2022-03-15 00:58 UTC, federicomiranda approved these changes
Perfecto 👌🏼

2022-03-15 00:59 UTC, merged